import { Checkbox } from "../../../components/ui/checkbox";
import type { ProcessorActivity, RequestPrincipal } from "./types";

export function ErasureChecklist({ principal, activities, checked, onChange }: { principal: RequestPrincipal; activities: ProcessorActivity[]; checked: ReadonlySet<string>; onChange: (key: string, value: boolean) => void }) {
  const sources = [...new Map(principal.fields.flatMap((field) => field.sources).map((source) => [source.id, source])).values()];
  const processors = activities.filter((activity) => activity.recipient.type === "DATA_PROCESSOR");
  const allItems = [...sources.map((source) => `source:${source.id}`), ...processors.map((processor) => `processor:${processor.recipient.id}`)];
  return <section className="rounded-md border p-4" aria-label="Erasure completion checklist"><h2 className="font-semibold">Erasure completion checklist</h2><p className="mt-1 text-sm text-muted-foreground">Confirm every source system and registered processor before marking this request complete. This records a human workflow; it does not delete anything.</p><div className="mt-3 space-y-2">{sources.map((source) => { const key = `source:${source.id}`; return <label key={key} className="flex gap-2 text-sm"><Checkbox type="checkbox" checked={checked.has(key)} onChange={(event) => onChange(key, event.target.checked)} />Source system: {source.name}</label>; })}{processors.map((processor) => { const key = `processor:${processor.recipient.id}`; return <label key={key} className="flex gap-2 text-sm"><Checkbox type="checkbox" checked={checked.has(key)} onChange={(event) => onChange(key, event.target.checked)} />Registered processor: {processor.recipient.name} — {processor.description}</label>; })}</div>{allItems.length === 0 ? <p className="mt-3 text-sm text-muted-foreground">No source systems or registered processors could be loaded; completion remains blocked pending this evidence.</p> : checked.size < allItems.length ? <p className="mt-3 text-sm text-destructive">Tick every listed item before completing.</p> : <p className="mt-3 text-sm text-emerald-700">All listed holders have been confirmed.</p>}</section>;
}
