/**
 * Every audit action MVP 1 can record, transcribed verbatim from
 * `DPDP_MVP1_FOUNDATION_AND_DISCOVERY.md` lines 880-891 -- a string-literal
 * union, not an enum of our own invention, so it stays byte-identical to
 * the spec's names.
 *
 * NOTE: the spec's §4.7 prose claims "33 MVP 1 action names", but the
 * fenced block at lines 880-891 lists 35 distinct names (11 of its 12
 * lines carry 3 names each, one line carries 2 -- 11*3+2=35). Per the task
 * brief's explicit instruction to "transcribe the names exactly" rather
 * than reconcile the count, this union originally contained all 35 names
 * that actually appear in the block. Task 16 adds the single authorized
 * extension `MATCH_CANDIDATE_CREATED`: candidate creation is a real state
 * change, and neither CONFIRMED nor REJECTED truthfully describes it.
 *
 * MVP 2 task 1 appends the 32 action names listed by the MVP 2 task 1
 * brief (compliance rules, notices, consent, guardians/children, rights
 * requests, erasure, campaigns, breach, SDF pack, Board/Government) below
 * the MVP 1 block, unchanged and unreordered.
 */
export type AuditAction =
  | "EMPLOYEE_LOGIN_SUCCEEDED"
  | "EMPLOYEE_LOGIN_FAILED"
  | "PRINCIPAL_LOGIN_SUCCEEDED"
  | "EMPLOYEE_CREATED"
  | "EMPLOYEE_DISABLED"
  | "EMPLOYEE_ROLE_CHANGED"
  | "ORG_SETTINGS_UPDATED"
  | "SDF_STATUS_DECLARED"
  | "THIRD_SCHEDULE_CLASS_DECLARED"
  | "PURPOSE_CREATED"
  | "PURPOSE_UPDATED"
  | "PURPOSE_REVIEWED"
  | "DATA_SOURCE_CREATED"
  | "DATA_SOURCE_UPDATED"
  | "DATA_SOURCE_DELETED"
  | "DATA_SOURCE_CREDENTIALS_ROTATED"
  | "FIELD_MAPPING_UPDATED"
  | "RECIPIENT_CREATED"
  | "RECIPIENT_UPDATED"
  | "SHARING_ACTIVITY_CREATED"
  | "TRANSFER_CREATED"
  | "RETENTION_POLICY_CREATED"
  | "SECURITY_MEASURE_UPDATED"
  | "SYNC_STARTED"
  | "SYNC_COMPLETED"
  | "SYNC_FAILED"
  | "PRINCIPAL_CREATED"
  | "IDENTITY_LINKED"
  | "IDENTITY_DETACHED"
  | "MATCH_CANDIDATE_CREATED"
  | "MATCH_CANDIDATE_CONFIRMED"
  | "MATCH_CANDIDATE_REJECTED"
  | "AGE_STATUS_SET"
  | "PERSONAL_DATA_VIEWED"
  | "EVIDENCE_EXPORTED"
  | "TOKEN_REUSE_DETECTED"
  // ── MVP 2 (task 1) ──
  | "COMPLIANCE_RULE_CHANGED"
  | "COMPLIANCE_RULE_REVIEWED"
  | "NOTICE_PUBLISHED"
  | "NOTICE_VERSION_CREATED"
  | "CONSENT_GRANTED"
  | "CONSENT_WITHDRAWN"
  | "CONSENT_DENIED"
  | "CONSENT_IMPORTED"
  | "GUARDIAN_REGISTERED"
  | "GUARDIAN_VERIFIED"
  | "CHILD_EXEMPTION_CLAIMED"
  | "REQUEST_CREATED"
  | "REQUEST_STATUS_CHANGED"
  | "REQUEST_IDENTITY_VERIFIED"
  | "REQUEST_FLAGGED_FRIVOLOUS"
  | "ACCESS_REPORT_GENERATED"
  | "ERASURE_TASK_CREATED"
  | "ERASURE_TASK_COMPLETED"
  | "LEGAL_HOLD_CREATED"
  | "CAMPAIGN_CREATED"
  | "CAMPAIGN_APPROVED"
  | "CAMPAIGN_SENT"
  | "TEMPLATE_UPDATED"
  | "BREACH_CREATED"
  | "BREACH_OBLIGATION_COMPLETED"
  | "BREACH_EXTENSION_RECORDED"
  | "BREACH_CLOSED"
  | "SDF_ASSESSMENT_COMPLETED"
  | "ALGORITHM_REGISTER_UPDATED"
  | "INFORMATION_REQUEST_RECORDED"
  | "NON_DISCLOSURE_SUPPRESSION_APPLIED"
  | "NOMINATION_UPDATED";

/**
 * All action names as a runtime array, for tests and validation: 36 from
 * MVP 1 plus 32 from MVP 2 task 1 (68 total).
 */
export const AUDIT_ACTIONS: readonly AuditAction[] = [
  "EMPLOYEE_LOGIN_SUCCEEDED",
  "EMPLOYEE_LOGIN_FAILED",
  "PRINCIPAL_LOGIN_SUCCEEDED",
  "EMPLOYEE_CREATED",
  "EMPLOYEE_DISABLED",
  "EMPLOYEE_ROLE_CHANGED",
  "ORG_SETTINGS_UPDATED",
  "SDF_STATUS_DECLARED",
  "THIRD_SCHEDULE_CLASS_DECLARED",
  "PURPOSE_CREATED",
  "PURPOSE_UPDATED",
  "PURPOSE_REVIEWED",
  "DATA_SOURCE_CREATED",
  "DATA_SOURCE_UPDATED",
  "DATA_SOURCE_DELETED",
  "DATA_SOURCE_CREDENTIALS_ROTATED",
  "FIELD_MAPPING_UPDATED",
  "RECIPIENT_CREATED",
  "RECIPIENT_UPDATED",
  "SHARING_ACTIVITY_CREATED",
  "TRANSFER_CREATED",
  "RETENTION_POLICY_CREATED",
  "SECURITY_MEASURE_UPDATED",
  "SYNC_STARTED",
  "SYNC_COMPLETED",
  "SYNC_FAILED",
  "PRINCIPAL_CREATED",
  "IDENTITY_LINKED",
  "IDENTITY_DETACHED",
  "MATCH_CANDIDATE_CREATED",
  "MATCH_CANDIDATE_CONFIRMED",
  "MATCH_CANDIDATE_REJECTED",
  "AGE_STATUS_SET",
  "PERSONAL_DATA_VIEWED",
  "EVIDENCE_EXPORTED",
  "TOKEN_REUSE_DETECTED",
  // ── MVP 2 (task 1) ──
  "COMPLIANCE_RULE_CHANGED",
  "COMPLIANCE_RULE_REVIEWED",
  "NOTICE_PUBLISHED",
  "NOTICE_VERSION_CREATED",
  "CONSENT_GRANTED",
  "CONSENT_WITHDRAWN",
  "CONSENT_DENIED",
  "CONSENT_IMPORTED",
  "GUARDIAN_REGISTERED",
  "GUARDIAN_VERIFIED",
  "CHILD_EXEMPTION_CLAIMED",
  "REQUEST_CREATED",
  "REQUEST_STATUS_CHANGED",
  "REQUEST_IDENTITY_VERIFIED",
  "REQUEST_FLAGGED_FRIVOLOUS",
  "ACCESS_REPORT_GENERATED",
  "ERASURE_TASK_CREATED",
  "ERASURE_TASK_COMPLETED",
  "LEGAL_HOLD_CREATED",
  "CAMPAIGN_CREATED",
  "CAMPAIGN_APPROVED",
  "CAMPAIGN_SENT",
  "TEMPLATE_UPDATED",
  "BREACH_CREATED",
  "BREACH_OBLIGATION_COMPLETED",
  "BREACH_EXTENSION_RECORDED",
  "BREACH_CLOSED",
  "SDF_ASSESSMENT_COMPLETED",
  "ALGORITHM_REGISTER_UPDATED",
  "INFORMATION_REQUEST_RECORDED",
  "NON_DISCLOSURE_SUPPRESSION_APPLIED",
  "NOMINATION_UPDATED",
];
