import type { Notification } from "@prisma/client";

/**
 * Who a `Notification` row belongs to. Deliberately narrower than
 * Prisma's `ActorType` enum (`EMPLOYEE | PRINCIPAL | SYSTEM`): every
 * `Notification` this module writes is addressed to exactly one employee
 * or one data principal (spec line 768's "someone with no email address
 * still receives everything" presupposes a *someone*). A caller wanting
 * to notify a group (e.g. "every ADMIN", spec line 588) calls `send()`
 * once per recipient -- there is no broadcast/SYSTEM-audience row type
 * here. See task-5-report.md "Concerns" for why this was left to callers.
 */
export type NotificationAudience = "EMPLOYEE" | "PRINCIPAL";

/** Free-text severity vocabulary observed in the spec (line 588: "raises
 * a CRITICAL notification"). `Notification.severity` is a plain
 * `String @default("INFO")` in the schema, not a Prisma enum, so this is
 * a caller-facing convention, not a DB constraint. */
export type NotificationSeverity = "INFO" | "WARNING" | "CRITICAL";

/**
 * Input every `NotificationProvider` implementation (and
 * `NotificationsService.send`, the single method Tasks 6, 9, 11, 14 and
 * 15 all call) accepts. `organizationId` is deliberately absent: every
 * write here goes through `prisma.scoped`, which reads the current
 * organization from `TenantContext` -- callers running outside an HTTP
 * request (a cron job, e.g. `deadline-scan`) are responsible for wrapping
 * their own call in `TenantContext.run(...)`, exactly like
 * `sync-pipeline.service.ts` already does elsewhere in this codebase.
 */
export interface NotificationSendInput {
  audience: NotificationAudience;
  /** Required (and the only recipient field used) when `audience` is `"EMPLOYEE"`. */
  employeeId?: string | null;
  /** Required (and the only recipient field used) when `audience` is `"PRINCIPAL"`. */
  dataPrincipalId?: string | null;
  title: string;
  body: string;
  /** Defaults to `"INFO"`. */
  severity?: NotificationSeverity;
  /** Frontend deep link, e.g. `/me/requests/REQ-000123`. */
  linkPath?: string | null;
  /** Set when this notification was generated by a `MessageCampaign` send. */
  campaignId?: string | null;
  /**
   * The recipient's email address, if the caller has one. NEVER required
   * -- portal-first (spec line 768): a principal with no email address
   * still gets the portal row, and the absence of an address here is
   * never an error, just a reason the email channel has nothing to do.
   * Recording a `NO_ADDRESS` suppression against a specific delivery
   * record (e.g. `CampaignRecipient`) is the calling task's job, not
   * this module's -- see `NotificationSendResult.reason` below for the
   * signal it can key that off of.
   */
  emailAddress?: string | null;
}

export type NotificationChannel = "PORTAL" | "EMAIL";

export interface NotificationSendResult {
  channel: NotificationChannel;
  /** `false` only for the `EMAIL` channel with no address supplied, or a
   * caught delivery failure -- `PortalProvider` always returns `true`
   * (or throws; it never returns `delivered: false`). */
  delivered: boolean;
  /** Set when `delivered` is `false`. Today the only value produced is
   * `"NO_ADDRESS"`; a delivery-failure path returns no result at all
   * (see `NotificationsService.send`'s doc comment for why: the error is
   * swallowed at that layer, not surfaced as a result). */
  reason?: "NO_ADDRESS";
  /** Set only by `PortalProvider` -- the row it just wrote, which is the
   * system of record for this notification. */
  notification?: Notification;
}

/**
 * One delivery channel for a notification. Three implementations exist:
 * `PortalProvider` (`channel: "PORTAL"`, always runs, unconditionally,
 * for every message -- see its own docstring), and exactly one of
 * `SmtpProvider` / `ConsoleProvider` (`channel: "EMAIL"`, selected by
 * `MAIL_TRANSPORT` via `selectEmailProvider` in
 * `email-provider.factory.ts`).
 */
export interface NotificationProvider {
  readonly channel: NotificationChannel;
  send(input: NotificationSendInput): Promise<NotificationSendResult>;
}
