/**
 * Idempotent demo seed: the full permission catalogue, the five system
 * roles with their exact default permission map, the Acme Retail demo
 * organization, and its five demo employee accounts.
 *
 * Run via the RAW (unscoped) `PrismaService` deliberately -- there is no
 * tenant context yet at seed time (the organization itself is being
 * created), which is exactly the case the raw client exists for. Every
 * write here uses `upsert` keyed on a natural/composite unique constraint
 * so a second run changes nothing: no new rows, no row updated to a
 * different value (an existing Employee's password hash is never
 * regenerated by re-running this script).
 *
 * Run with `npx ts-node prisma/seed.ts` (or via `npx prisma db seed` once
 * wired into package.json's `prisma.seed` field).
 */
import * as argon2 from "argon2";
import { PrismaService } from "../src/common/prisma/prisma.service";
import { PERMISSIONS } from "./seed/permissions";
import { ROLES } from "./seed/roles";
import { DEMO_EMPLOYEES, DEMO_ORG, DEMO_PASSWORD } from "./seed/demo-org";
import { seedComplianceRules } from "./seed/compliance-rules";
import { seedMessageTemplates } from "./seed/message-templates";

async function seedPermissions(prisma: PrismaService): Promise<void> {
  for (const permission of PERMISSIONS) {
    await prisma.permission.upsert({
      where: { code: permission.code },
      create: permission,
      update: {
        description: permission.description,
        category: permission.category,
      },
    });
  }
}

async function seedOrganization(prisma: PrismaService): Promise<string> {
  const existing = await prisma.organization.findFirst({
    where: { name: DEMO_ORG.name },
  });
  if (existing) {
    return existing.id;
  }
  const created = await prisma.organization.create({ data: DEMO_ORG });
  return created.id;
}

async function seedRoles(
  prisma: PrismaService,
  organizationId: string,
): Promise<Record<string, string>> {
  const roleIdByCode: Record<string, string> = {};

  for (const role of ROLES) {
    const upserted = await prisma.role.upsert({
      where: { organizationId_code: { organizationId, code: role.code } },
      create: {
        organizationId,
        code: role.code,
        name: role.name,
        isSystem: role.isSystem,
      },
      update: { name: role.name, isSystem: role.isSystem },
    });
    roleIdByCode[role.code] = upserted.id;

    for (const permissionCode of role.permissionCodes) {
      await prisma.rolePermission.upsert({
        where: {
          roleId_permissionCode: { roleId: upserted.id, permissionCode },
        },
        create: { roleId: upserted.id, permissionCode },
        update: {},
      });
    }
  }

  return roleIdByCode;
}

async function seedDemoEmployees(
  prisma: PrismaService,
  organizationId: string,
  roleIdByCode: Record<string, string>,
): Promise<void> {
  for (const employee of DEMO_EMPLOYEES) {
    const existing = await prisma.employee.findFirst({
      where: { organizationId, email: employee.email },
    });
    if (existing) {
      continue;
    }
    const roleId = roleIdByCode[employee.roleCode];
    if (!roleId) {
      throw new Error(
        `seed.ts: no seeded role found for code "${employee.roleCode}" -- ` +
          "check ROLES in prisma/seed/roles.ts.",
      );
    }
    const passwordHash = await argon2.hash(DEMO_PASSWORD, {
      type: argon2.argon2id,
    });
    await prisma.employee.create({
      data: {
        organizationId,
        email: employee.email,
        fullName: employee.fullName,
        roleId,
        passwordHash,
        status: "ACTIVE",
      },
    });
  }
}

/**
 * Runs the full seed against an already-connected `PrismaService` and
 * returns the demo organization's id. Exported (not just called from
 * `main` below) so `test/employee-auth.e2e-spec.ts` can call it twice in
 * a row against the real database and assert row counts are unchanged the
 * second time -- the brief's idempotency test.
 */
export async function runSeed(prisma: PrismaService): Promise<{
  organizationId: string;
}> {
  await seedPermissions(prisma);
  const organizationId = await seedOrganization(prisma);
  const roleIdByCode = await seedRoles(prisma, organizationId);
  await seedDemoEmployees(prisma, organizationId, roleIdByCode);
  await seedComplianceRules(prisma, organizationId);
  await seedMessageTemplates(prisma, organizationId);
  return { organizationId };
}

async function main(): Promise<void> {
  const prisma = new PrismaService();
  await prisma.$connect();
  try {
    const { organizationId } = await runSeed(prisma);
    // eslint-disable-next-line no-console
    console.log(
      `Seed complete. Organization ${organizationId} ("${DEMO_ORG.name}").`,
    );
  } finally {
    await prisma.$disconnect();
  }
}

if (require.main === module) {
  main().catch((error) => {
    // eslint-disable-next-line no-console
    console.error(error);
    process.exitCode = 1;
  });
}
