import { INestApplication } from "@nestjs/common";
import { performance } from "node:perf_hooks";
import request from "supertest";
import { PrismaService } from "../src/common/prisma/prisma.service";
import { bootstrapTestApp, waitUntil } from "./support/e2e-harness";
import {
  SCALE_APPROVER_EMAIL,
  SCALE_EMPLOYEE_PASSWORD,
  SCALE_OPERATOR_EMAIL,
  SCALE_ORG_NAME,
  SCALE_PRINCIPAL_COUNT,
  SCALE_CONSENT_COUNT,
} from "../scripts/seed-scale";

/**
 * Check 36: realistic-scale performance gates.  This suite intentionally
 * runs only when the explicit `RUN_SCALE_PERFORMANCE=1` opt-in is present;
 * the 12,000/40,000 fixture is generated by `scripts/seed-scale.ts` and is
 * not silently created inside Jest.  Every assertion below measures the
 * real HTTP endpoint (and, for campaign delivery, the real BullMQ worker)
 * against the seeded tenant.
 */
const describeScale =
  process.env["RUN_SCALE_PERFORMANCE"] === "1" ? describe : describe.skip;

describeScale("Check 36: performance at realistic scale", () => {
  jest.setTimeout(120_000);

  let app: INestApplication;
  let prisma: PrismaService;
  let organizationId: string;
  let operatorToken: string;
  let approverToken: string;
  let purposeId: string;
  let evidencePrincipalId: string;

  beforeAll(async () => {
    const testApp = await bootstrapTestApp();
    app = testApp.app;
    prisma = testApp.prisma;

    const organization = await prisma.organization.findFirst({
      where: { name: SCALE_ORG_NAME },
      select: { id: true },
    });
    if (!organization) {
      throw new Error(
        `Check 36 requires ${SCALE_ORG_NAME}; run scripts/seed-scale.ts first.`,
      );
    }
    organizationId = organization.id;
    const [principalCount, consentCount] = await Promise.all([
      prisma.dataPrincipal.count({ where: { organizationId } }),
      prisma.consentRecord.count({ where: { organizationId } }),
    ]);
    expect(principalCount).toBe(SCALE_PRINCIPAL_COUNT);
    expect(consentCount).toBe(SCALE_CONSENT_COUNT);

    const [operator, approver, purpose, principal] = await Promise.all([
      prisma.employee.findUnique({
        where: {
          organizationId_email: { organizationId, email: SCALE_OPERATOR_EMAIL },
        },
        select: { email: true },
      }),
      prisma.employee.findUnique({
        where: {
          organizationId_email: { organizationId, email: SCALE_APPROVER_EMAIL },
        },
        select: { email: true },
      }),
      prisma.processingPurpose.findFirst({
        where: { organizationId, code: "SCALE_PURPOSE_1" },
        select: { id: true },
      }),
      prisma.dataPrincipal.findFirst({
        where: { organizationId, reference: "SCALE-DP-000001" },
        select: { id: true },
      }),
    ]);
    if (!operator || !approver || !purpose || !principal) {
      throw new Error(
        "Check 36 scale fixture is incomplete; rerun scripts/seed-scale.ts.",
      );
    }
    purposeId = purpose.id;
    evidencePrincipalId = principal.id;

    const login = async (email: string): Promise<string> => {
      const response = await request(app.getHttpServer())
        .post("/api/auth/employee/login")
        .send({ email, password: SCALE_EMPLOYEE_PASSWORD });
      expect(response.status).toBe(200);
      return response.body.accessToken as string;
    };
    [operatorToken, approverToken] = await Promise.all([
      login(operator.email),
      login(approver.email),
    ]);
  });

  afterAll(async () => {
    await app?.close();
    await prisma?.$disconnect();
  });

  it("audience preview is below 1.5 seconds", async () => {
    const startedAt = performance.now();
    const response = await request(app.getHttpServer())
      .post("/api/audiences/preview")
      .set("Authorization", `Bearer ${operatorToken}`)
      .send({
        filter: {
          op: "AND",
          rules: [
            { field: "ageStatus", operator: "eq", value: "ADULT" },
            { field: "hasEmail", operator: "eq", value: true },
          ],
        },
        purposeId,
      });
    const elapsedMs = performance.now() - startedAt;
    expect(response.status).toBe(201);
    expect(response.body.total).toBe(SCALE_PRINCIPAL_COUNT);
    expect(elapsedMs).toBeLessThan(1_500);
  });

  it("request dashboard (list plus stats) is below 800 milliseconds", async () => {
    const startedAt = performance.now();
    const [list, stats] = await Promise.all([
      request(app.getHttpServer())
        .get("/api/requests")
        .set("Authorization", `Bearer ${operatorToken}`),
      request(app.getHttpServer())
        .get("/api/requests/stats")
        .set("Authorization", `Bearer ${operatorToken}`),
    ]);
    const elapsedMs = performance.now() - startedAt;
    expect(list.status).toBe(200);
    expect(stats.status).toBe(200);
    expect(elapsedMs).toBeLessThan(800);
  });

  it("evidence page is below one second", async () => {
    const startedAt = performance.now();
    const response = await request(app.getHttpServer())
      .get(`/api/principals/${evidencePrincipalId}/evidence`)
      .set("Authorization", `Bearer ${operatorToken}`);
    const elapsedMs = performance.now() - startedAt;
    expect(response.status).toBe(200);
    expect(response.body.principal.id).toBe(evidencePrincipalId);
    expect(elapsedMs).toBeLessThan(1_000);
  });

  it("a 2,000-recipient campaign is fully delivered within 60 seconds", async () => {
    const unique = Date.now();
    const startedAt = performance.now();
    // CITY is a deterministic marker written by seed-scale.ts for exactly
    // 2,000 principals; this avoids relying on database row ordering.
    const measuredCreate = await request(app.getHttpServer())
      .post("/api/campaigns")
      .set("Authorization", `Bearer ${operatorToken}`)
      .send({
        name: `Check 36 measured campaign ${unique}`,
        category: "COMPLIANCE_NOTICE",
        subject: "Check 36 performance message",
        bodyMarkdown: "This is a Check 36 performance message.",
        audienceFilter: {
          op: "AND",
          rules: [
            {
              field: "city",
              operator: "eq",
              value: "PERFORMANCE_CAMPAIGN_2000",
            },
          ],
        },
      });
    expect(measuredCreate.status).toBe(201);
    expect(measuredCreate.body.recipientCount).toBe(2_000);
    const campaignId = measuredCreate.body.id as string;

    const approve = await request(app.getHttpServer())
      .post(`/api/campaigns/${campaignId}/approve`)
      .set("Authorization", `Bearer ${approverToken}`)
      .send({});
    expect(approve.status).toBe(201);
    const send = await request(app.getHttpServer())
      .post(`/api/campaigns/${campaignId}/send`)
      .set("Authorization", `Bearer ${operatorToken}`)
      .send({});
    expect(send.status).toBe(201);

    await waitUntil(
      async () => {
        const [campaign, delivered] = await Promise.all([
          prisma.messageCampaign.findUnique({
            where: { id: campaignId },
            select: { status: true },
          }),
          prisma.campaignRecipient.count({
            where: { campaignId, status: "DELIVERED" },
          }),
        ]);
        return campaign?.status === "SENT" && delivered === 2_000;
      },
      59_000,
      100,
    );
    const elapsedMs = performance.now() - startedAt;
    expect(elapsedMs).toBeLessThan(60_000);
  });
});
