import { useState } from "react";
import { useMutation, useQueries, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { ApiError, employeeApiClient } from "../../lib/api-client";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../../components/ui/card";
import { Input } from "../../components/ui/input";
import { Label } from "../../components/ui/label";
import { Select } from "../../components/ui/select";
import { PermissionGate } from "../../components/shared/PermissionGate";

interface Purpose { id: string; name: string; code: string; lawfulBasis: "CONSENT" | "LEGITIMATE_USE"; description: string; }
interface ConsentStats { purposeId: string; total: number; granted: number; denied: number; withdrawn: number; unknown: number; }
function errorMessage(error: unknown) { return error instanceof ApiError && error.message ? error.message : "Could not record imported consent."; }

/** `/app/consents` — consent-purpose totals plus an auditable imported-consent writer. */
export function ConsentsPage() {
  const queryClient = useQueryClient(); const [principalId, setPrincipalId] = useState(""); const [purposeId, setPurposeId] = useState(""); const [status, setStatus] = useState<"GRANTED" | "DENIED" | "WITHDRAWN">("GRANTED"); const [channel, setChannel] = useState("IMPORTED"); const [noticeId, setNoticeId] = useState("");
  const { data: purposes = [], isLoading } = useQuery({ queryKey: ["purposes"], queryFn: () => employeeApiClient.get<Purpose[]>("/purposes") });
  const consentPurposes = purposes.filter((purpose) => purpose.lawfulBasis === "CONSENT");
  const stats = useQueries({ queries: consentPurposes.map((purpose) => ({ queryKey: ["consent-stats", purpose.id], queryFn: () => employeeApiClient.get<ConsentStats>(`/purposes/${purpose.id}/consent-stats`) })) });
  const record = useMutation({ mutationFn: () => employeeApiClient.post(`/principals/${principalId}/consents/${purposeId}`, { status, channel, noticeId: (status === "GRANTED" || status === "DENIED") ? noticeId || undefined : undefined }), onSuccess: () => { toast.success("Imported consent recorded with an evidence event."); setPrincipalId(""); setNoticeId(""); void queryClient.invalidateQueries({ queryKey: ["consent-stats"] }); }, onError: (error) => toast.error(errorMessage(error)) });
  return <div className="space-y-6"><div><h1 className="text-xl font-semibold">Consents</h1><p className="text-sm text-muted-foreground">Only consent-basis purposes appear here. Missing evidence remains Unknown — never Denied.</p></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{isLoading ? <p className="text-sm text-muted-foreground">Loading consent purposes…</p> : consentPurposes.map((purpose, index) => { const data = stats[index]?.data; return <Card key={purpose.id}><CardHeader><CardTitle className="text-base">{purpose.name}</CardTitle><CardDescription>{purpose.code}</CardDescription></CardHeader><CardContent><div className="flex flex-wrap gap-2 text-sm"><Badge>Granted {data?.granted ?? "—"}</Badge><Badge variant="secondary">Unknown {data?.unknown ?? "—"}</Badge><Badge variant="outline">Denied {data?.denied ?? "—"}</Badge><Badge variant="outline">Withdrawn {data?.withdrawn ?? "—"}</Badge></div><p className="mt-3 text-xs text-muted-foreground">{data ? `${data.total} records` : "Loading totals…"}</p></CardContent></Card>; })}</div>
    {purposes.some((purpose) => purpose.lawfulBasis === "LEGITIMATE_USE") ? <Card><CardHeader><CardTitle className="text-base">Legitimate-use purposes</CardTitle><CardDescription>These have no consent record or consent toggle; their basis is explained in the purpose register.</CardDescription></CardHeader><CardContent><div className="flex flex-wrap gap-2">{purposes.filter((purpose) => purpose.lawfulBasis === "LEGITIMATE_USE").map((purpose) => <Badge key={purpose.id} variant="secondary">{purpose.name}</Badge>)}</div></CardContent></Card> : null}
    <PermissionGate permission="CAN_MANAGE_CONSENTS"><Card><CardHeader><CardTitle className="text-base">Record imported consent</CardTitle><CardDescription>For a decision captured outside the portal. Grant and decline require the published notice ID that was shown; a withdrawal may reuse its recorded notice.</CardDescription></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); record.mutate(); }}><div className="space-y-1"><Label htmlFor="principal-id">Principal ID</Label><Input id="principal-id" value={principalId} onChange={(event) => setPrincipalId(event.target.value)} required /></div><div className="space-y-1"><Label htmlFor="purpose-id">Consent purpose</Label><Select id="purpose-id" value={purposeId} onChange={(event) => setPurposeId(event.target.value)} required><option value="">Choose a purpose</option>{consentPurposes.map((purpose) => <option key={purpose.id} value={purpose.id}>{purpose.name}</option>)}</Select></div><div className="space-y-1"><Label htmlFor="consent-status">Decision</Label><Select id="consent-status" value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="GRANTED">Granted</option><option value="DENIED">Denied</option><option value="WITHDRAWN">Withdrawn</option></Select></div><div className="space-y-1"><Label htmlFor="consent-channel">Channel</Label><Select id="consent-channel" value={channel} onChange={(event) => setChannel(event.target.value)}><option value="IMPORTED">Imported</option><option value="EMAIL">Email</option><option value="IN_PERSON">In person</option><option value="API">API</option><option value="CONSENT_MANAGER">Consent manager</option></Select></div>{status !== "WITHDRAWN" ? <div className="space-y-1 md:col-span-2"><Label htmlFor="consent-notice-id">Published notice ID shown</Label><Input id="consent-notice-id" value={noticeId} onChange={(event) => setNoticeId(event.target.value)} required /></div> : null}<div><Button type="submit" disabled={record.isPending}>{record.isPending ? "Recording…" : "Record imported consent"}</Button></div></form></CardContent></Card></PermissionGate>
  </div>;
}
