import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { ApiError, employeeApiClient } from "../../lib/api-client";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../../components/ui/card";
import { Input } from "../../components/ui/input";
import { Label } from "../../components/ui/label";
import { Select } from "../../components/ui/select";
import { Textarea } from "../../components/ui/textarea";
import { PermissionGate } from "../../components/shared/PermissionGate";
import { NotReviewedChip } from "../components/NotReviewedChip";
import { humanizeEnum } from "../lib/enum-options";

interface ComplianceRule { id: string; ruleCode: string; version: number; name: string; legalSource: string; basis: "STATUTORY" | "SECTORAL" | "ORG_POLICY" | "INTERNAL_TARGET"; appliesTo: string; deadlineValue: number; deadlineUnit: "HOURS" | "DAYS" | "MONTHS" | "YEARS"; warningLead: number; publishedPeriodText: string | null; enabled: boolean; notes: string | null; isReviewed: boolean; reviewedAt: string | null; }
const RULE_14_3 = "DPDP Rules, 2025 — Rule 14(3): published period must not exceed ninety days.";
function errorMessage(error: unknown) { return error instanceof ApiError && error.message ? error.message : "Could not save this compliance rule."; }

function RuleCard({ rule }: { rule: ComplianceRule }) {
  const queryClient = useQueryClient(); const [editing, setEditing] = useState(false); const [value, setValue] = useState(String(rule.deadlineValue)); const [unit, setUnit] = useState(rule.deadlineUnit); const [warningLead, setWarningLead] = useState(String(rule.warningLead)); const [publishedPeriodText, setPublishedPeriodText] = useState(rule.publishedPeriodText ?? ""); const [notes, setNotes] = useState(rule.notes ?? ""); const [ceilingError, setCeilingError] = useState("");
  const save = useMutation({ mutationFn: () => employeeApiClient.patch(`/compliance-rules/${rule.id}`, { deadlineValue: Number(value), deadlineUnit: unit, warningLead: Number(warningLead), publishedPeriodText: publishedPeriodText || undefined, notes: notes || undefined }), onSuccess: () => { toast.success(`Saved ${rule.ruleCode} as version ${rule.version + 1}.`); setEditing(false); void queryClient.invalidateQueries({ queryKey: ["compliance-rules"] }); }, onError: (error) => toast.error(errorMessage(error)) });
  const review = useMutation({ mutationFn: () => employeeApiClient.post(`/compliance-rules/${rule.id}/review`), onSuccess: () => { toast.success("Rule review recorded."); void queryClient.invalidateQueries({ queryKey: ["compliance-rules"] }); }, onError: (error) => toast.error(errorMessage(error)) });
  function submit() { const number = Number(value); if (rule.ruleCode === "GRIEVANCE_RESPONSE" && unit === "DAYS" && number > 90) { setCeilingError(`The period cannot exceed 90 days. ${RULE_14_3}`); return; } setCeilingError(""); save.mutate(); }
  return <Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-base">{rule.name}</CardTitle><CardDescription>{rule.ruleCode} · version {rule.version} · {rule.appliesTo}</CardDescription></div><div className="flex items-center gap-2"><Badge variant={rule.basis === "STATUTORY" ? "default" : "secondary"}>{humanizeEnum(rule.basis)}</Badge><NotReviewedChip isReviewed={rule.isReviewed} /></div></div></CardHeader><CardContent className="space-y-3"><p className="text-sm"><span className="font-medium">Citation: </span>{rule.legalSource}</p>{editing ? <div className="grid gap-3 md:grid-cols-2"><div className="space-y-1"><Label htmlFor={`${rule.id}-deadline`}>Deadline</Label><Input id={`${rule.id}-deadline`} type="number" min="1" value={value} onChange={(event) => setValue(event.target.value)} /></div><div className="space-y-1"><Label htmlFor={`${rule.id}-unit`}>Unit</Label><Select id={`${rule.id}-unit`} value={unit} onChange={(event) => setUnit(event.target.value as typeof unit)}>{["HOURS", "DAYS", "MONTHS", "YEARS"].map((entry) => <option key={entry} value={entry}>{humanizeEnum(entry)}</option>)}</Select></div><div className="space-y-1"><Label htmlFor={`${rule.id}-warn`}>Warning lead</Label><Input id={`${rule.id}-warn`} type="number" min="0" value={warningLead} onChange={(event) => setWarningLead(event.target.value)} /></div><div className="space-y-1"><Label htmlFor={`${rule.id}-published`}>Published period text</Label><Input id={`${rule.id}-published`} value={publishedPeriodText} onChange={(event) => setPublishedPeriodText(event.target.value)} /></div><div className="space-y-1 md:col-span-2"><Label htmlFor={`${rule.id}-notes`}>Notes</Label><Textarea id={`${rule.id}-notes`} value={notes} onChange={(event) => setNotes(event.target.value)} /></div>{ceilingError ? <p className="md:col-span-2 text-sm text-destructive">{ceilingError}</p> : null}<div className="flex gap-2"><Button onClick={submit} disabled={save.isPending}>{save.isPending ? "Saving…" : "Save version"}</Button><Button variant="outline" onClick={() => setEditing(false)}>Cancel</Button></div></div> : <><p className="text-sm">Deadline: <span className="font-medium">{rule.deadlineValue} {humanizeEnum(rule.deadlineUnit)}</span> · warning {rule.warningLead}</p>{rule.publishedPeriodText ? <p className="text-sm text-muted-foreground">Published period: {rule.publishedPeriodText}</p> : null}<PermissionGate permission="CAN_CHANGE_COMPLIANCE_CONFIG"><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setEditing(true)}>Edit as new version</Button>{!rule.isReviewed ? <Button size="sm" onClick={() => review.mutate()} disabled={review.isPending}>Mark reviewed</Button> : null}</div></PermissionGate></>}<p className="text-xs text-muted-foreground">Editing creates version N+1. Existing requests and obligations retain their original rule snapshot.</p></CardContent></Card>;
}

/** `/app/settings/compliance` — transparent deadline configuration, never a compliance verdict. */
export function SettingsCompliancePage() {
  const { data: rules = [], isLoading } = useQuery({ queryKey: ["compliance-rules"], queryFn: () => employeeApiClient.get<ComplianceRule[]>("/compliance-rules") });
  return <div className="space-y-6"><div><h1 className="text-xl font-semibold">Compliance rules</h1><p className="text-sm text-muted-foreground">Every deadline carries its source, honest basis, and DPO review state. Editing makes a new version; it never moves an existing deadline.</p></div>{isLoading ? <p className="text-sm text-muted-foreground">Loading rules…</p> : rules.length === 0 ? <Card><CardContent className="p-6 text-sm text-muted-foreground">No deadline rules are configured. New operational records will show “No deadline rule configured”.</CardContent></Card> : <div className="space-y-4">{rules.map((rule) => <RuleCard key={rule.id} rule={rule} />)}</div>}</div>;
}
