import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { ApiError, employeeApiClient } from "../../lib/api-client";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../../components/ui/card";
import { Input } from "../../components/ui/input";
import { Label } from "../../components/ui/label";
import { Textarea } from "../../components/ui/textarea";
import { PermissionGate } from "../../components/shared/PermissionGate";

interface Organization { name: string; dpoName: string | null; dpoEmail: string | null; responsiblePersonName: string | null; responsiblePersonEmail: string | null; grievanceContactEmail: string | null; publicPrivacyPageUrl: string | null; }
function failure(error: unknown) { return error instanceof ApiError && error.message ? error.message : "Could not record the publication location."; }
function rightsText(org: Organization) { const contact = org.dpoEmail ?? org.responsiblePersonEmail ?? org.grievanceContactEmail ?? "[responsible contact email]"; return `Your rights and how to make a request\n\nYou may ask ${org.name} for access to, correction, completion, updating or erasure of your personal data; withdraw consent where consent is the basis; raise a grievance; or make a nomination where applicable.\n\nTo make a request, use our privacy request channel and provide the identifier we publish for verification (for example your registered email address, mobile number, or customer ID), together with enough detail to identify the request. We may ask for verification before acting.\n\nFor help or to raise a grievance, contact ${contact}. If you are not satisfied with our grievance response, you may approach the Data Protection Board of India.`; }
/** `/app/settings/rights` — generates publishable RT-01/RT-02 text but never publishes it for the company. */
export function SettingsRightsPage() {
  const queryClient = useQueryClient(); const { data: organization, isLoading } = useQuery({ queryKey: ["organization"], queryFn: () => employeeApiClient.get<Organization>("/organization") }); const [publishedUrl, setPublishedUrl] = useState("");
  const save = useMutation({ mutationFn: () => employeeApiClient.patch("/organization", { publicPrivacyPageUrl: publishedUrl || undefined }), onSuccess: () => { toast.success("Publication location recorded."); void queryClient.invalidateQueries({ queryKey: ["organization"] }); }, onError: (error) => toast.error(failure(error)) });
  if (isLoading || !organization) return <p className="text-sm text-muted-foreground">Loading rights publication settings…</p>;
  return <div className="space-y-6"><div><h1 className="text-xl font-semibold">Rights publication</h1><p className="text-sm text-muted-foreground">Generate the public-facing rights text, then record where your company publishes it.</p></div><Card><CardHeader><CardTitle className="text-base">Public-facing rights text</CardTitle><CardDescription>RT-01/RT-02 content for the company website or privacy page. Review it before publishing.</CardDescription></CardHeader><CardContent><Textarea aria-label="Public-facing rights text" value={rightsText(organization)} readOnly className="min-h-80 font-mono text-xs" /><p className="mt-3 rounded-md bg-muted p-3 text-sm">This platform cannot publish to your website. Copy this text to your chosen public location, then record that location below.</p></CardContent></Card><PermissionGate permission="CAN_CHANGE_ORG_SETTINGS" fallback={<Card><CardContent className="p-4 text-sm text-muted-foreground">Publication location: {organization.publicPrivacyPageUrl ?? "Not recorded"}</CardContent></Card>}><Card><CardHeader><CardTitle className="text-base">Publication location</CardTitle><CardDescription>This records where the company says it published the rights text; it does not verify or publish the page.</CardDescription></CardHeader><CardContent><form className="flex flex-col gap-3 sm:flex-row sm:items-end" onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><div className="flex-1 space-y-1"><Label htmlFor="rights-public-url">Public URL</Label><Input id="rights-public-url" type="url" value={publishedUrl || organization.publicPrivacyPageUrl || ""} onChange={(event) => setPublishedUrl(event.target.value)} placeholder="https://example.com/privacy" required /></div><Button type="submit" disabled={save.isPending}>{save.isPending ? "Recording…" : "Record publication URL"}</Button></form></CardContent></Card></PermissionGate></div>;
}
